# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85373b530c83ea442803a3a37d51a466d38cfc20143192093c4b739a6a006b8e3bb38217dd0f5d02a8f0807ea1d166c58769d44543778e8dfe4c9c8a1fb394f0

test:
  secret_key_base: 1bef7c1f77e301bfeeac4dff764b95dcaad3db5bff01932405b2818497054e0a83519d2f2fed48a92ab162ff32fbfe774354ba0c349a3b89c19bbb9e2d6e004a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
